# Generated by Django 4.2.3 on 2023-07-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
