# Generated by Django 4.2.3 on 2023-07-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='OTP',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
